### PR TITLE
Support dovetail of OPNFV in CIRA.

### PR DESCRIPTION
**Pull request by s1061123**
Add docker-compose-dovetail.yml for containers with dovetail,
OPNFV test driver for OPNFV trademark. centos7_dovetail is newly
introduced to create dovetail container based on CentOS.

Signed-off-by: Tomofumi Hayashi <tohayash@redhat.com>

### CODE REVIEW

**Comment by leifmadsen** [comment]
Note that I ran the Project Atomic Dockerfile linter across the new Dockerfile, and here is the output in case you want to clean some of that up:

```
docker run -it --rm --privileged -v `pwd`:/root/ projectatomic/dockerfile-lint dockerfile_lint -f centos7_dovetail
```

```
--------ERRORS---------

ERROR: Required LABEL name/key 'Name' is not defined. 
Reference -> http://docs.projectatomic.io/container-best-practices/#_recommended_labels_for_your_project


ERROR: Required LABEL name/key 'Version' is not defined. 
Reference -> http://docs.projectatomic.io/container-best-practices/#_recommended_labels_for_your_project



-------WARNINGS--------

Line 17: -> RUN yum update -y &&     yum install -y sudo iproute epel-release &&     yum install -y openssh openssh-server openssh-clients &&     yum install -y python-pip git docker-engine-1.9.1-1.el7.centos &&     sed -ie 's/requiretty/!requiretty/g' /etc/sudoers &&     pip install pyyaml click jinja2 &&     git config --global http.sslVerify false &&     git clone https://gerrit.opnfv.org/gerrit/dovetail.git ${REPOS_DIR} &&     mkdir -p ${REPOS_DIR}/results
WARNING: yum clean all is not used. the yum cache will remain in this layer making the layer unnecessarily large. 
Reference -> http://docs.projectatomic.io/container-best-practices/#_clear_packaging_caches_and_temporary_package_downloads


Line 17: -> RUN yum update -y &&     yum install -y sudo iproute epel-release &&     yum install -y openssh openssh-server openssh-clients &&     yum install -y python-pip git docker-engine-1.9.1-1.el7.centos &&     sed -ie 's/requiretty/!requiretty/g' /etc/sudoers &&     pip install pyyaml click jinja2 &&     git config --global http.sslVerify false &&     git clone https://gerrit.opnfv.org/gerrit/dovetail.git ${REPOS_DIR} &&     mkdir -p ${REPOS_DIR}/results
WARNING: installing SSH in a container is not recommended. Do you really need SSH in this image?. 
Reference -> https://github.com/jpetazzo/nsenter



--------INFO---------

Line 17: -> RUN yum update -y &&     yum install -y sudo iproute epel-release &&     yum install -y openssh openssh-server openssh-clients &&     yum install -y python-pip git docker-engine-1.9.1-1.el7.centos &&     sed -ie 's/requiretty/!requiretty/g' /etc/sudoers &&     pip install pyyaml click jinja2 &&     git config --global http.sslVerify false &&     git clone https://gerrit.opnfv.org/gerrit/dovetail.git ${REPOS_DIR} &&     mkdir -p ${REPOS_DIR}/results
INFO: updating the entire base image may add unnecessary size to the container. update the entire base image may add unnecessary size to the container. 
Reference -> http://docs.projectatomic.io/container-best-practices/#_clear_packaging_caches_and_temporary_package_downloads


INFO: Maintainer is not defined. The MAINTAINER line is useful for identifying the author in the form of MAINTAINER Joe Smith <joe.smith@example.com>. 
Reference -> https://docs.docker.com/reference/builder/#maintainer


INFO: There is no 'EXPOSE' instruction. Without exposed ports how will the service of the container be accessed?. 
Reference -> https://docs.docker.com/reference/builder/#expose


INFO: There is no 'CMD' instruction. None. 
Reference -> https://docs.docker.com/reference/builder/#cmd

```

**Comment by leifmadsen** [comment]
Generally I think this is ok, but we're going to want to be careful about setting a precedent here about adding containers this way.

Ideally we should create a proper pipeline and push the containers into something like Docker Hub and consume them that way rather than using them like a poor mans virtual machine.

CC: @dougbtv

**Comment by s1061123** [comment]
Hi Leif,

Thank you for your comment! Regarding linter issues, I will fix them.
Regarding container's proper pipeline, we need to discuss more from now to future hence
let me open new enhancement issue in github to track on it.

**Comment by leifmadsen** [comment]
+1 yea in the future we'll want to change our container pipeline, but not right now :)

**Comment by dougbtv** [comment]
Just chiming in to say I'm following along. I'm hopeful to get some traction on ansible-cira to grok it and hopefully be able to give some input on the pipeline for images and container instances when I get it. I do understand that you're consuming external ansible roles to provision and there's some pragmatism here for the moment. So, I'm keeping that in mind.

**Pull request merged**
